[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi|~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[general]
import = ["/home/marcel/.config/alacritty/catppuccin/catppuccin-frappe.toml"]

[cursor.style]
blinking = "on"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 8.0

[font.bold]
family = "terminal"
style = "Bold"

[font.bold_italic]
family = "terminal"
style = "Bold Italic"

[font.italic]
family = "terminal"
style = "Italic"

[font.normal]
#family = "JetBransMono Nerd Font"
family = "terminal"
style = "Regular"


[window.padding]
x = 0
y = 0

[keyboard]
